# -*- coding: utf-8 -*-
"""25.1.GS.JOAO.LUCAS.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j9-kTRgWwBY2WyMyw7GKWcZJlOR9ekH
"""

tipos_desastres = []
paises = []
cidades = []
bairros = []
ruas = []
total_afetados = []
criancas = []
adultos = []
idosos = []
mobilidade_reduzida = []
feridos = []

quantidade = int(input("Quantos desastres você quer registrar? "))


for i in range(quantidade):
    print(f"\nDesastre {i + 1}:")

    tipos_desastres.append(input("Tipo de desastre: "))
    paises.append(input("País: "))
    cidades.append(input("Cidade: "))
    bairros.append(input("Bairro: "))
    ruas.append(input("Rua: "))

    while True:
        total = int(input("Quantidade total de pessoas afetadas: "))
        c = int(input("Quantidade de crianças: "))
        a = int(input("Quantidade de adultos: "))
        idoso = int(input("Quantidade de idosos: "))
        m = int(input("Quantidade de pessoas com mobilidade reduzida: "))
        f = int(input("Quantidade de feridos: "))

        soma = c + a + idoso + m + f

        if soma == total:
            total_afetados.append(total)
            criancas.append(c)
            adultos.append(a)
            idosos.append(idoso)
            mobilidade_reduzida.append(m)
            feridos.append(f)
            break
        else:
            print("\n Erro: A soma das categorias não corresponde ao total de pessoas afetadas. Tente novamente.\n")

print("\n Dados registrados com sucesso!")